name: Build & Push Utils Service

on:
  push:
    branches:
      - main
    paths:
      - "services/utils/**"

jobs:
  build-utils:
    name: Build & Push Utils Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push utils image
        uses: docker/build-push-action@v5
        with:
          context: ./services/utils
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/foodify-utils-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/foodify-utils-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger Render Deploy
        run: curl ${{ secrets.RENDER_UTILS_DEPLOY_HOOK }}
